/* Generated by scripts/build-docs-engine.js — do not edit by hand. */
/* src/extract.js */
/**
 * Content extraction engine — Content-Derived Design.
 *
 * This module deliberately has no DOM or Node-only dependency so the exact
 * extraction contract can run in the CLI, playground, and browser extension.
 * It extracts content first, then derives a readable palette from those
 * signals. It never invents source facts.
 */

var COLOR_NAMES = {
  red: '#c23a2a', crimson: '#a0141e', scarlet: '#b22234', maroon: '#6b1f1a',
  blue: '#2563eb', navy: '#1a2138', cobalt: '#1c3d6e', indigo: '#312e81', azure: '#0e7ec0',
  green: '#16a34a', forest: '#166534', olive: '#4d7c0f', sage: '#4a7c59', mint: '#6ee7b7',
  teal: '#0d9488', cyan: '#0891b2', turquoise: '#0fb5c4', aquamarine: '#7fffd4',
  yellow: '#eab308', gold: '#e8a63f', amber: '#d97706', honey: '#e8b647',
  orange: '#ea580c', coral: '#f43f5e', rust: '#b45309', copper: '#b87333',
  purple: '#7c3aed', violet: '#8b5cf6', plum: '#6b2c6b', magenta: '#c026d3', lavender: '#a78bfa',
  pink: '#ec4899', rose: '#e11d48', blush: '#fda4af', salmon: '#fa8072',
  brown: '#78350f', chocolate: '#3d2817', coffee: '#4a2c2a', mocha: '#7b5e3c', tan: '#d4a373',
  cream: '#f4ecd8', ivory: '#fffef0', beige: '#e8dcc4', parchment: '#f1e9d2', linen: '#faf0e6',
  white: '#ffffff', snow: '#fafafa',
  black: '#0a0a0a', charcoal: '#1a1a1a', obsidian: '#0d0d0d', onyx: '#161616',
  gray: '#6b7280', grey: '#6b7280', slate: '#334155', stone: '#78716c', ash: '#b2b2b2',
  silver: '#c0c0c0', platinum: '#e5e4e2',
  sand: '#e2c9a0', clay: '#c67a3d', earth: '#6b5d4f', wood: '#96633a',
  navy2: '#0a1626', sky: '#38bdf8', ocean: '#0e7490', sea: '#1e5f74',
};

var PROFILE_PALETTES = {
  saas:       { ground: '#0a1626', accent: '#6ee7b7', muted: '#3b82f6', surface: '#111f38', ink: '#e2e8f0' },
  tech:       { ground: '#0d1117', accent: '#a78bfa', muted: '#38bdf8', surface: '#161b27', ink: '#e6edf3' },
  essay:      { ground: '#f8f5ef', accent: '#a0141e', muted: '#4a3c2a', surface: '#efe9df', ink: '#1a1612' },
  literary:   { ground: '#f1ece1', accent: '#6b1f1a', muted: '#5c4a2a', surface: '#e8e0d0', ink: '#1f1a14' },
  food:       { ground: '#faf6ef', accent: '#b45309', muted: '#4d7c0f', surface: '#f0e8d8', ink: '#1a1612' },
  restaurant: { ground: '#1a1612', accent: '#d97706', muted: '#b45309', surface: '#241e16', ink: '#f4ecd8' },
  nature:     { ground: '#f3f6f0', accent: '#166534', muted: '#4d7c0f', surface: '#e6ede0', ink: '#1a2118' },
  outdoor:    { ground: '#0d1f14', accent: '#4ade80', muted: '#16a34a', surface: '#142819', ink: '#e8f0e4' },
  ocean:      { ground: '#062838', accent: '#38bdf8', muted: '#0891b2', surface: '#0d3a52', ink: '#e0f2fe' },
  night:      { ground: '#0a0a14', accent: '#8b5cf6', muted: '#6366f1', surface: '#12121e', ink: '#e0e0f0' },
  editorial:  { ground: '#fffbf5', accent: '#1a1612', muted: '#b45309', surface: '#f5f0e6', ink: '#1a1612' },
  minimal:    { ground: '#fafafa', accent: '#1a1a1a', muted: '#6b7280', surface: '#f0f0f0', ink: '#1a1a1a' },
  default:    { ground: '#1a1a2e', accent: '#e8a63f', muted: '#6366f1', surface: '#24243e', ink: '#f4ecd8' },
};

var STOP_NOUNS = new Set([
  'this','that','with','from','have','been','were','they','their','about','which','there','would','could',
  'should','other','some','only','also','more','into','over','after','before','between','through','during',
  'above','below','under','your','our','what','when','where','while','since','until','upon','within',
  'without','these','those','them','then','than','here','will','just','like','make','made','take','taken',
  'give','given','come','came','went','goes','gone','said','says','say','see','seen','saw','get','got','put',
  'set','let','may','might','must','shall','need','used','uses','using','want','wants','know','knows','known',
  'think','thinks','thought','feel','feels','felt','look','looks','looked','seem','seems','seemed','find','found',
  'work','works','worked','call','called','each','many','much','very','such','same','both','either','neither',
  'even','still','back','away','down','once','done','well','way','own','too','yet','per','via','from',
]);

var STOP_PROPER = new Set([
  'The','This','That','And','But','For','From','With','When','Where','What','How','Who','Which','There',
  'Their','These','Those','About','After','Before','During','While','Since','Until','Above','Below','Under',
  'Over','Into','Upon','Within','Without','They','Them','Are','Was','Were','Been','Have','Has','Had','Will',
  'Would','Could','Should','May','Might','Can','Did','Does','Not','Yes','Get','Set','Put','Use','See','Try',
  'Open','More','Most','Some','Any','All','New','Old','One','Two','Three','Here','Your','Our','Its','Content',
  'Design','Source','Read','Run','Play','Drag','Timeline','Statistical','Poster','Data','Signal','Item',
]);

function isHex(value) {
  return typeof value === 'string' && /^#[0-9a-f]{3,8}$/i.test(value);
}

function canonicalHex(value) {
  if (!isHex(value)) return null;
  var c = value.toLowerCase();
  if (c.length === 4) return '#' + c[1] + c[1] + c[2] + c[2] + c[3] + c[3];
  if (c.length === 5) return '#' + c[1] + c[1] + c[2] + c[2] + c[3] + c[3];
  if (c.length === 7) return c;
  if (c.length === 9) return c.slice(0, 7);
  return null;
}

function hexToRgb(hex) {
  var c = canonicalHex(hex) || '#000000';
  return {
    r: parseInt(c.slice(1, 3), 16),
    g: parseInt(c.slice(3, 5), 16),
    b: parseInt(c.slice(5, 7), 16),
  };
}

function rgbToHex(r, g, b) {
  return '#' + [r, g, b].map(function(value) {
    value = Math.max(0, Math.min(255, Math.round(value)));
    return value.toString(16).padStart(2, '0');
  }).join('');
}

function relativeLuminance(rgb) {
  function channel(value) {
    value /= 255;
    return value <= 0.03928 ? value / 12.92 : Math.pow((value + 0.055) / 1.055, 2.4);
  }
  return 0.2126 * channel(rgb.r) + 0.7152 * channel(rgb.g) + 0.0722 * channel(rgb.b);
}

function contrastRatio(hex1, hex2) {
  var l1 = relativeLuminance(hexToRgb(hex1));
  var l2 = relativeLuminance(hexToRgb(hex2));
  return (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05);
}

function isLight(hex) { return relativeLuminance(hexToRgb(hex)) > 0.42; }

function tint(hex, amount) {
  var c = hexToRgb(hex);
  return rgbToHex(c.r + (255 - c.r) * amount, c.g + (255 - c.g) * amount, c.b + (255 - c.b) * amount);
}

function shade(hex, amount) {
  var c = hexToRgb(hex);
  return rgbToHex(c.r * (1 - amount), c.g * (1 - amount), c.b * (1 - amount));
}

function ensureContrast(ground, color, target) {
  target = target || 4.5;
  ground = canonicalHex(ground) || '#10131a';
  color = canonicalHex(color) || (isLight(ground) ? '#1a1612' : '#f4ecd8');
  if (contrastRatio(ground, color) >= target) return color;

  var lightGround = isLight(ground);
  var adjusted = color;
  for (var i = 0; i < 28; i++) {
    adjusted = lightGround ? shade(adjusted, 0.06) : tint(adjusted, 0.06);
    if (contrastRatio(ground, adjusted) >= target) return adjusted;
  }
  return lightGround ? '#1a1612' : '#f4ecd8';
}

function decodeEntities(value) {
  return String(value || '').replace(/&(#x[0-9a-f]+|#\d+|amp|lt|gt|quot|apos|nbsp);/gi, function(_, entity) {
    var lower = entity.toLowerCase();
    if (lower === 'amp') return '&';
    if (lower === 'lt') return '<';
    if (lower === 'gt') return '>';
    if (lower === 'quot') return '"';
    if (lower === 'apos') return "'";
    if (lower === 'nbsp') return ' ';
    var number = lower.indexOf('#x') === 0 ? parseInt(lower.slice(2), 16) : parseInt(lower.slice(1), 10);
    return Number.isFinite(number) && number >= 0 && number <= 0x10ffff ? String.fromCodePoint(number) : '';
  });
}

function cleanFragment(value) {
  return decodeEntities(String(value || '').replace(/<[^>]*>/g, ' ')).replace(/\s+/g, ' ').trim();
}

function filenameTitle(filePath) {
  var raw = String(filePath || '').split(/[\\/]/).pop() || '';
  raw = raw.replace(/\.[^.]+$/, '').replace(/^before$/i, '');
  return raw.replace(/[-_]+/g, ' ').trim() || 'Untitled';
}

function uniquePush(list, value) {
  if (value && list.indexOf(value) === -1) list.push(value);
}

function profileName(lowerText) {
  if (/observability|traces?|infrastructure|deploy|kubernetes|pipeline|latency|uptime|metrics?|saas|api|sdk/.test(lowerText)) return 'saas';
  if (/tech|software|code|programming|developer|engineer|framework|library|runtime|compiler|algorithm/.test(lowerText)) return 'tech';
  if (/lighthouse|journal|diary|letter|correspondence|reflection|personal/.test(lowerText)) return 'essay';
  if (/essay|memoir|narrative|prose|literary|chapter|story|told|wrote|author|poem|poetry|verse/.test(lowerText)) return 'literary';
  if (/menu|recipe|dish|restaurant|kitchen|chef|flavor|taste|cuisine|dining|served|saffron|smoke/.test(lowerText)) return 'restaurant';
  if (/food|cook|bake|ingredient|meal|delicious|spice|herb/.test(lowerText)) return 'food';
  if (/forest|tree|mountain|river|trail|hike|camp|wilderness|outdoor|nature|garden/.test(lowerText)) return 'nature';
  if (/ocean|sea|marine|wave|coast|beach|surf|sail|diving|reef|coral/.test(lowerText)) return 'ocean';
  if (/night|dark|midnight|moon|star|shadow|void|dream|nocturnal/.test(lowerText)) return 'night';
  if (/editorial|magazine|article|column|feature|issue|press|news/.test(lowerText)) return 'editorial';
  return 'default';
}

function readablePalette(palette) {
  var ground = canonicalHex(palette.ground) || '#10131a';
  var light = isLight(ground);
  var ink = ensureContrast(ground, palette.ink, 4.5);
  var accent = ensureContrast(ground, palette.accent, 3);
  var muted = ensureContrast(ground, palette.muted, 2.5);
  var surface = canonicalHex(palette.surface) || (light ? shade(ground, 0.05) : tint(ground, 0.08));
  if (contrastRatio(ground, surface) < 1.08) surface = light ? shade(ground, 0.07) : tint(ground, 0.12);
  return { ground: ground, accent: accent, muted: muted, surface: surface, ink: ink };
}

function derivePalette(lowerText, sourceHex, foundColors) {
  var profile = profileName(lowerText);
  var base = PROFILE_PALETTES[profile];

  if (sourceHex.length >= 3) {
    var ground = sourceHex[0];
    var accent = sourceHex[1];
    var muted = sourceHex[2] || base.muted;
    var surface = sourceHex[3] || (isLight(ground) ? shade(ground, 0.05) : tint(ground, 0.12));
    var ink = isLight(ground) ? '#0a0a0a' : '#f4ecd8';
    return readablePalette({ ground: ground, accent: accent, muted: muted, surface: surface, ink: ink });
  }

  if (foundColors.length >= 2) {
    var lightColor = foundColors.find(function(hex) { return isLight(hex); });
    var darkColor = foundColors.find(function(hex) { return !isLight(hex); });
    var ground2 = base.ground;
    var accent2 = isLight(ground2) ? (darkColor || foundColors[0]) : (lightColor || darkColor || foundColors[0]);
    return readablePalette({
      ground: ground2,
      accent: accent2,
      muted: foundColors[2] || base.muted,
      surface: isLight(ground2) ? shade(ground2, 0.05) : tint(ground2, 0.08),
      ink: isLight(ground2) ? '#0a0a0a' : '#f4ecd8',
    });
  }

  return readablePalette(base);
}

function extractContent(html, filePath) {
  html = String(html == null ? '' : html);

  var sourceWithoutNoise = html
    .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '')
    .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, '')
    .replace(/<!--[\s\S]*?-->/g, '');
  var text = cleanFragment(sourceWithoutNoise);
  var lower = text.toLowerCase();

  var titleMatch = html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  var h1Match = html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);
  var h2Match = html.match(/<h2[^>]*>([\s\S]*?)<\/h2>/i);
  var title = cleanFragment(titleMatch ? titleMatch[1] : h1Match ? h1Match[1] : h2Match ? h2Match[1] : '');
  if (!title) title = filenameTitle(filePath);

  var headings = [];
  var headingRe = /<h([1-3])[^>]*>([\s\S]*?)<\/h\1>/gi;
  var headingMatch;
  while ((headingMatch = headingRe.exec(html)) !== null) {
    var heading = cleanFragment(headingMatch[2]);
    if (heading.length > 2) uniquePush(headings, heading);
  }

  var paragraphs = [];
  var paragraphRe = /<p[^>]*>([\s\S]*?)<\/p>/gi;
  var paragraphMatch;
  while ((paragraphMatch = paragraphRe.exec(sourceWithoutNoise)) !== null) {
    var paragraph = cleanFragment(paragraphMatch[1]);
    if (paragraph.length > 20) uniquePush(paragraphs, paragraph);
  }

  var items = [];
  var itemRe = /<li[^>]*>([\s\S]*?)<\/li>/gi;
  var itemMatch;
  while ((itemMatch = itemRe.exec(sourceWithoutNoise)) !== null) {
    var item = cleanFragment(itemMatch[1]);
    if (item.length > 2) uniquePush(items, item);
  }

  var links = [];
  var linkRe = /<a\b([^>]*)>([\s\S]*?)<\/a>/gi;
  var linkMatch;
  while ((linkMatch = linkRe.exec(sourceWithoutNoise)) !== null) {
    var hrefMatch = linkMatch[1].match(/\bhref\s*=\s*["']([^"']+)["']/i);
    if (!hrefMatch) continue;
    var href = hrefMatch[1].trim();
    if (!/^(?:https?:|mailto:|#|\/)/i.test(href)) continue;
    var label = cleanFragment(linkMatch[2]);
    if (label || href) {
      var duplicate = links.some(function(existing) { return existing.href === href; });
      if (!duplicate) links.push({ label: label || href, href: href });
    }
  }

  var emails = [];
  var emailRe = /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/g;
  var emailMatch;
  while ((emailMatch = emailRe.exec(text)) !== null) uniquePush(emails, emailMatch[0]);

  var dates = [];
  var dateRe = /\b(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2}(?:st|nd|rd|th)?,?\s+(?:18|19|20)\d{2}\b|\b(?:18|19|20)\d{2}\b/gi;
  var dateMatch;
  while ((dateMatch = dateRe.exec(text)) !== null) uniquePush(dates, dateMatch[0]);

  var numbers = [];
  var numberRe = /\b\d+(?:[,.]\d+)?\s*(?:ms|s|min|hr|hours?|days?|weeks?|months?|years?|seats?|users?|people|persons?|dollars?|usd|eur|gbp|gb|mb|kb|px|em|rem|rpm|acres|miles|km|metres|meters|feet|ft|pounds?|kg|g|oz|%|x|k|m|b)\b/gi;
  var numberMatch;
  while ((numberMatch = numberRe.exec(text)) !== null) uniquePush(numbers, numberMatch[0]);
  var significantRe = /\b\d{2,}(?:\.\d+)?\b/g;
  var significantMatch;
  while ((significantMatch = significantRe.exec(text)) !== null) {
    var significant = significantMatch[0];
    if (!dates.some(function(date) { return date.indexOf(significant) >= 0; })) uniquePush(numbers, significant);
  }

  var properNouns = [];
  var properRe = /\b[A-Z][a-zA-Z]{2,}(?:\s+[A-Z][a-zA-Z]{2,}){0,2}\b/g;
  var properMatch;
  while ((properMatch = properRe.exec(text)) !== null) {
    var proper = properMatch[0].trim();
    var parts = proper.split(/\s+/);
    if (parts.some(function(part) { return STOP_PROPER.has(part); })) {
      parts = parts.filter(function(part) { return !STOP_PROPER.has(part); });
      proper = parts.join(' ');
    }
    if (proper.length > 2) uniquePush(properNouns, proper);
  }

  var foundColors = [];
  Object.keys(COLOR_NAMES).forEach(function(name) {
    if (new RegExp('\\b' + name + '\\b', 'i').test(lower)) uniquePush(foundColors, COLOR_NAMES[name]);
  });

  // CSS hex values are useful, but do not let a source page's framework
  // neutrals (white/black/gray) become the new visual ground. Keep a compact,
  // chromatic list for content-derived palette decisions.
  var chromaticColors = foundColors.filter(function(hex) {
    var rgb = hexToRgb(hex);
    var max = Math.max(rgb.r, rgb.g, rgb.b);
    var min = Math.min(rgb.r, rgb.g, rgb.b);
    return max - min >= 28 && max > 35 && min < 245;
  });

  var sourceHex = [];
  var hexRe = /#[0-9a-fA-F]{3,8}\b/g;
  var hexMatch;
  while ((hexMatch = hexRe.exec(html)) !== null) uniquePush(sourceHex, canonicalHex(hexMatch[0]));

  var frequency = {};
  text.split(/\s+/).forEach(function(word) {
    var noun = word.replace(/[^a-zA-Z]/g, '').toLowerCase();
    if (noun.length > 3 && !STOP_NOUNS.has(noun)) frequency[noun] = (frequency[noun] || 0) + 1;
  });
  var nouns = Object.keys(frequency)
    .sort(function(a, b) { return frequency[b] - frequency[a] || a.localeCompare(b); })
    .slice(0, 10)
    .map(function(noun) { return noun.charAt(0).toUpperCase() + noun.slice(1); });

  var anchors = [];
  properNouns.forEach(function(value) { if (anchors.length < 5) uniquePush(anchors, value); });
  nouns.forEach(function(value) { if (anchors.length < 5) uniquePush(anchors, value); });
  if (!anchors.length) anchors = ['Content', 'Design', 'Source'];

  var profile = profileName(lower);
  return {
    title: title,
    headings: headings.slice(0, 12),
    paragraphs: paragraphs.slice(0, 8),
    items: items.slice(0, 16),
    links: links.slice(0, 12),
    emails: emails.slice(0, 5),
    dates: dates.slice(0, 10),
    numbers: numbers.slice(0, 10),
    properNouns: properNouns.slice(0, 10),
    nouns: nouns,
    anchors: anchors.slice(0, 5),
    palette: derivePalette(lower, sourceHex, chromaticColors),
    foundColors: foundColors,
    sourceHex: sourceHex.slice(0, 10),
    sourceText: text.slice(0, 8000),
    profile: profile,
    density: paragraphs.length + items.length > 12 ? 'rich' : paragraphs.length + items.length > 4 ? 'medium' : 'sparse',
    hasTimeline: dates.length >= 2,
    hasMetrics: numbers.length >= 2,
    hasContact: emails.length > 0,
  };
}

var extractApi = {
  extractContent: extractContent,
  hexToRgb: hexToRgb,
  rgbToHex: rgbToHex,
  relativeLuminance: relativeLuminance,
  contrastRatio: contrastRatio,
  isLight: isLight,
  tint: tint,
  shade: shade,
  ensureContrast: ensureContrast,
  PROFILE_PALETTES: PROFILE_PALETTES,
  COLOR_NAMES: COLOR_NAMES,
};

if (typeof module !== 'undefined' && module.exports) module.exports = extractApi;
if (typeof window !== 'undefined') window.ReimagineExtract = extractApi;

/* src/generate.js */
/**
 * Token-specific standalone HTML generators.
 *
 * The engine keeps one promise across every output form: the source is the
 * brief. Visible facts come from the extracted content; visual variation comes
 * from a deterministic draw when a seed is supplied, or a fresh draw otherwise.
 */

var extractApi = typeof module !== 'undefined' && module.exports
  ? require('./extract')
  : (typeof window !== 'undefined' ? window.ReimagineExtract : {});

var tint = extractApi.tint;
var shade = extractApi.shade;
var isLight = extractApi.isLight;
var ensureContrast = extractApi.ensureContrast;

var TOKENS = [
  'webpage', 'landing', 'dashboard', 'infographic', 'cinematic',
  'artistic', 'photography', 'svg', '3js', 'simulation',
];

var TOKEN_DESCRIPTIONS = {
  webpage: 'Measured editorial page for reading the source',
  landing: 'Product-style page with source-backed actions and features',
  dashboard: 'Operational view built from source facts and counts',
  infographic: 'Common-scale poster for dates, facts, and comparisons',
  cinematic: 'Scroll-led narrative with chapters from the source',
  artistic: 'Expressive poster with an anchor-derived visual field',
  photography: 'Visual folio of abstract studies, one per source anchor',
  svg: 'Inline living diagram with a labeled anchor network',
  '3js': 'Offline canvas object with pointer and keyboard orbit',
  simulation: 'Playable sequence or date timeline from the source',
};

function list(value) {
  return Array.isArray(value) ? value.filter(function(item) { return item !== null && item !== undefined && String(item).trim(); }).map(String) : [];
}

function color(value, fallback) {
  return typeof value === 'string' && /^#[0-9a-f]{3,8}$/i.test(value) ? value.slice(0, 7) : fallback;
}

function normaliseContent(input) {
  input = input || {};
  var palette = input.palette || {};
  return {
    title: String(input.title || 'Untitled'),
    headings: list(input.headings),
    paragraphs: list(input.paragraphs),
    items: list(input.items),
    links: Array.isArray(input.links) ? input.links.filter(function(link) {
      return link && typeof link.href === 'string' && typeof link.label === 'string';
    }).map(function(link) { return { href: link.href, label: link.label }; }) : [],
    emails: list(input.emails),
    dates: list(input.dates),
    numbers: list(input.numbers),
    properNouns: list(input.properNouns),
    nouns: list(input.nouns),
    anchors: list(input.anchors),
    profile: String(input.profile || 'default'),
    density: String(input.density || 'medium'),
    palette: {
      ground: color(palette.ground, '#10131a'),
      accent: color(palette.accent, '#e8a63f'),
      muted: color(palette.muted, '#778094'),
      surface: color(palette.surface, '#1a202b'),
      ink: color(palette.ink, '#f4ecd8'),
    },
  };
}

function generate(opts) {
  opts = opts || {};
  var content = normaliseContent(opts.content);
  var token = TOKENS.indexOf(opts.token) >= 0 ? opts.token : 'webpage';
  var brief = opts.brief ? String(opts.brief) : '';
  var p = content.palette;
  var ground = p.ground;
  var accent = ensureContrast(ground, p.accent, 3);
  var muted = ensureContrast(ground, p.muted, 2.5);
  var surface = p.surface;
  var ink = ensureContrast(ground, p.ink, 4.5);
  var rng = makeRNG(opts.seed !== undefined ? opts.seed : Math.floor(Math.random() * 0x7fffffff));
  var anchors = shuffle(content.anchors.length ? content.anchors : ['Content', 'Design', 'Source'], rng);
  var paragraphs = shuffle(content.paragraphs, rng);
  var items = shuffle(content.items, rng);
  var facts = factsFor(content);
  var profile = content.profile;
  var label = brief || profileLabel(profile);
  var variation = {
    drift: Math.round(rng() * 24 - 12),
    radius: Math.round(rng() * 10 + 2),
    tilt: Math.round(rng() * 8 - 4),
    offset: Math.round(rng() * 18 + 8),
  };

  var craftFloor = '::selection{background:' + accent + ';color:' + ground + '}' +
    ':focus-visible{outline:2px solid ' + accent + ';outline-offset:4px;border-radius:3px}' +
    '@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important;scroll-behavior:auto!important}}';
  var baseCss = '*{box-sizing:border-box;margin:0;padding:0}' +
    'html{background:var(--g);color:var(--i);-webkit-font-smoothing:antialiased}' +
    'body{min-height:100vh;overflow-x:hidden}' +
    'a{color:var(--a);text-underline-offset:3px}' +
    'button,input{font:inherit}' +
    '.source-block,.section,.feature,.plate,.metric{content-visibility:auto;contain-intrinsic-size:0 180px}' +
    '@media(max-width:640px){body{overflow-wrap:anywhere}}';
  var serif = '"Iowan Old Style","Hoefler Text",Palatino,Georgia,Cambria,serif';
  var sans = 'ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif';
  var mono = 'ui-monospace,"SF Mono","Cascadia Code",Consolas,Menlo,monospace';
  var svgSans = sans.replace(/"/g, '');

  switch (token) {
    case 'webpage': return webpage();
    case 'landing': return landing();
    case 'dashboard': return dashboard();
    case 'infographic': return infographic();
    case 'cinematic': return cinematic();
    case 'artistic': return artistic();
    case 'photography': return photography();
    case 'svg': return svg();
    case '3js': return threejs();
    case 'simulation': return simulation();
    default: return webpage();
  }

  function page(title, css, body, script) {
    return '<!doctype html><html lang="en"><head><meta charset="utf-8">' +
      '<meta name="viewport" content="width=device-width,initial-scale=1">' +
      '<meta name="color-scheme" content="' + (isLight(ground) ? 'light' : 'dark') + '">' +
      '<title>' + esc(title) + '</title><style>' +
      ':root{--g:' + ground + ';--a:' + accent + ';--m:' + muted + ';--s:' + surface + ';--i:' + ink + ';--drift:' + variation.drift + 'px;--radius:' + variation.radius + 'px}' +
      baseCss + css + craftFloor + '</style></head><body>' + body +
      (script ? '<scr' + 'ipt>' + script + '</scr' + 'ipt>' : '') +
      '</body></html>';
  }

  function paragraphAt(index, anchor) {
    return paragraphs.length ? paragraphs[index % paragraphs.length] : 'Source anchor: ' + anchor + '.';
  }

  function sectionId(value, index) {
    return 'section-' + index + '-' + String(value).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 28);
  }

  function usefulLink() {
    for (var i = 0; i < content.links.length; i++) {
      if (/^(?:https?:|mailto:|#)/i.test(content.links[i].href)) return content.links[i];
    }
    return null;
  }

  function linkList() {
    return content.links.slice(0, 5).map(function(link) {
      return '<li><a href="' + esc(link.href) + '">' + esc(link.label) + '</a></li>';
    }).join('');
  }

  function webpage() {
    var light = isLight(ground);
    var border = light ? 'rgba(15,18,24,.14)' : 'rgba(255,255,255,.14)';
    var sections = anchors.map(function(anchor, index) {
      var id = sectionId(anchor, index);
      return '<article class="section" id="' + id + '" style="--n:' + index + '">' +
        '<div class="section-index">' + String(index + 1).padStart(2, '0') + '</div>' +
        '<div><h2>' + esc(anchor) + '</h2><p>' + esc(paragraphAt(index, anchor)) + '</p>' +
        (facts[index] && facts[index].value ? '<p class="fact"><span>' + esc(facts[index].kind) + '</span> ' + esc(facts[index].value) + '</p>' : '') +
        '</div></article>';
    }).join('');
    var contents = anchors.map(function(anchor, index) {
      return '<a href="#' + sectionId(anchor, index) + '">' + esc(anchor) + '</a>';
    }).join('');
    var sourceLinks = content.links.length ? '<aside class="source-block"><span class="eyebrow">Source links</span><ul>' + linkList() + '</ul></aside>' : '';
    var css = 'body{font-family:' + sans + ';background:var(--g);color:var(--i)}' +
      '.page{max-width:920px;margin:0 auto;padding:clamp(28px,7vw,92px) 28px 100px}' +
      '.hero{display:grid;grid-template-columns:minmax(0,1fr) 180px;gap:44px;align-items:end;padding-bottom:64px;border-bottom:1px solid ' + border + '}' +
      '.eyebrow{display:block;font:10px ' + mono + ';letter-spacing:.18em;text-transform:uppercase;color:var(--m);margin-bottom:18px}' +
      '.hero h1{font:400 clamp(44px,8vw,90px)/.92 ' + serif + ';letter-spacing:-.045em;max-width:9ch;color:var(--a);text-wrap:balance}' +
      '.lede{max-width:54ch;font-size:18px;line-height:1.7;opacity:.78;margin-top:26px}' +
      '.stamp{align-self:start;justify-self:end;border:1px solid ' + border + ';border-radius:var(--radius);padding:16px;font:10px/1.6 ' + mono + ';color:var(--m);transform:translateY(var(--drift)) rotate(' + variation.tilt + 'deg)}' +
      '.stamp strong{display:block;font-size:30px;line-height:1;color:var(--a);margin-bottom:8px}' +
      '.contents{display:flex;gap:12px;flex-wrap:wrap;padding:22px 0 12px;font:11px ' + mono + ';text-transform:uppercase;letter-spacing:.08em}' +
      '.contents a{color:var(--m);text-decoration:none;border-bottom:1px solid transparent}.contents a:hover{color:var(--a);border-color:var(--a)}' +
      '.section{display:grid;grid-template-columns:70px minmax(0,1fr);gap:24px;padding:46px 0;border-bottom:1px solid ' + border + '}' +
      '.section-index{font:12px ' + mono + ';color:var(--a);padding-top:7px}' +
      '.section h2{font:400 clamp(26px,4vw,42px)/1 ' + serif + ';letter-spacing:-.025em;margin-bottom:16px}' +
      '.section p{max-width:62ch;font-size:16px;line-height:1.75;opacity:.76}' +
      '.section .fact{font:11px ' + mono + ';color:var(--a);opacity:1;margin-top:18px;text-transform:uppercase;letter-spacing:.08em}' +
      '.section .fact span{color:var(--m);margin-right:8px}' +
      '.source-block{margin-top:46px;padding:22px 0;border-top:1px solid ' + border + '}' +
      '.source-block ul{display:flex;gap:16px;flex-wrap:wrap;list-style:none;font-size:13px}' +
      '@media(max-width:700px){.hero{grid-template-columns:1fr}.stamp{justify-self:start;transform:none}.section{grid-template-columns:42px 1fr;gap:12px}}';
    return page(content.title, css, '<main class="page"><header class="hero"><div><span class="eyebrow">' + esc(label) + '</span><h1>' + esc(content.title) + '</h1><p class="lede">' + esc(paragraphAt(0, anchors[0])) + '</p></div><div class="stamp"><strong>' + anchors.length + '</strong>source<br>anchors</div></header><nav class="contents" aria-label="On this page">' + contents + '</nav>' + sections + sourceLinks + '</main>');
  }

  function landing() {
    var light = isLight(ground);
    var border = light ? 'rgba(15,18,24,.12)' : 'rgba(255,255,255,.14)';
    var action = usefulLink();
    var primaryHref = action ? action.href : '#features';
    var primaryText = action ? (action.href.indexOf('mailto:') === 0 ? 'Contact source' : 'Open source ↗') : 'Explore ' + anchors[0];
    var features = anchors.slice(0, 4).map(function(anchor, index) {
      var item = items[index] || paragraphAt(index, anchor);
      return '<article class="feature"><span class="feature-no">0' + (index + 1) + '</span><h2>' + esc(anchor) + '</h2><p>' + esc(item) + '</p></article>';
    }).join('');
    var css = 'body{font-family:' + sans + ';background:var(--g);color:var(--i)}' +
      '.landing{max-width:1080px;margin:0 auto;padding:24px 28px 90px}' +
      '.topline{display:flex;justify-content:space-between;gap:16px;padding:16px 0;border-bottom:1px solid ' + border + ';font:10px ' + mono + ';letter-spacing:.15em;text-transform:uppercase;color:var(--m)}' +
      '.hero{position:relative;padding:clamp(72px,12vw,150px) 0 100px;max-width:850px}' +
      '.hero::before{content:"";position:absolute;width:440px;height:300px;left:calc(36% + var(--drift));top:12%;background:radial-gradient(ellipse,' + accent + '28,transparent 68%);pointer-events:none;filter:blur(2px)}' +
      '.hero>*{position:relative}' +
      '.eyebrow{font:10px ' + mono + ';letter-spacing:.2em;text-transform:uppercase;color:var(--a)}' +
      'h1{font:400 clamp(52px,10vw,122px)/.88 ' + serif + ';letter-spacing:-.055em;max-width:10ch;margin-top:20px;text-wrap:balance}' +
      '.lede{max-width:52ch;font-size:19px;line-height:1.65;opacity:.75;margin-top:28px}' +
      '.actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:34px}' +
      '.action{display:inline-flex;align-items:center;gap:8px;padding:14px 20px;border-radius:999px;background:var(--a);color:var(--g);font-weight:700;text-decoration:none;transition:transform .18s ease,box-shadow .18s ease}' +
      '.action:hover{transform:translateY(-3px);box-shadow:0 18px 34px -16px ' + accent + '}' +
      '.action.secondary{background:transparent;color:var(--i);box-shadow:inset 0 0 0 1px ' + border + '}' +
      '.feature-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:0;border-top:1px solid ' + border + ';border-bottom:1px solid ' + border + '}' +
      '.feature{padding:28px 20px 34px 0;border-right:1px solid ' + border + ';margin-right:20px}' +
      '.feature:last-child{border-right:0;margin-right:0}' +
      '.feature-no{font:11px ' + mono + ';color:var(--a)}' +
      '.feature h2{font:400 26px/1 ' + serif + ';letter-spacing:-.02em;margin:40px 0 12px}' +
      '.feature p{font-size:14px;line-height:1.65;opacity:.68}' +
      '.links{margin-top:48px;font-size:13px}.links ul{display:flex;gap:18px;flex-wrap:wrap;list-style:none;margin-top:14px}' +
      '@media(max-width:800px){.feature-grid{grid-template-columns:repeat(2,1fr)}.feature:nth-child(2){border-right:0;margin-right:0}.feature:nth-child(n+3){border-top:1px solid ' + border + '}}' +
      '@media(max-width:480px){.feature-grid{grid-template-columns:1fr}.feature{border-right:0!important;margin-right:0!important;border-top:1px solid ' + border + '}.feature:first-child{border-top:0}}';
    var links = content.links.length ? '<section class="links"><span class="eyebrow">Continue with the source</span><ul>' + linkList() + '</ul></section>' : '';
    return page(content.title, css, '<main class="landing"><div class="topline"><span>' + esc(label) + '</span><span>' + anchors.length + ' source signals</span></div><header class="hero"><span class="eyebrow">' + esc(content.profile) + '</span><h1>' + esc(content.title) + '</h1><p class="lede">' + esc(paragraphAt(0, anchors[0])) + '</p><div class="actions"><a class="action" href="' + esc(primaryHref) + '">' + esc(primaryText) + ' →</a><a class="action secondary" href="#features">See the signals</a></div></header><section class="feature-grid" id="features" aria-label="Source features">' + features + '</section>' + links + '</main>');
  }

  function dashboard() {
    var dGround = isLight(ground) ? shade(ground, .78) : ground;
    var dAccent = ensureContrast(dGround, accent, 3);
    var dMuted = ensureContrast(dGround, muted, 2.5);
    var dSurface = tint(dGround, .07);
    var metrics = metricCards(facts, anchors);
    var cards = metrics.map(function(metric, index) {
      return '<article class="metric kpi"><span class="metric-kind">' + esc(metric.kind) + '</span><strong>' + esc(metric.value) + '</strong><h2>' + esc(metric.label) + '</h2><div class="metric-foot">' + esc(metric.detail) + '<svg viewBox="0 0 120 28" aria-hidden="true"><path d="' + sparkPath(metric.label, index) + '"/></svg></div></article>';
    }).join('');
    var css = 'body{font-family:' + sans + ';background:var(--g);color:var(--i)}' +
      '.console{max-width:1080px;margin:0 auto;padding:clamp(28px,6vw,72px) 28px 90px}' +
      '.console-head{display:flex;justify-content:space-between;align-items:end;gap:24px;border-bottom:1px solid rgba(255,255,255,.12);padding-bottom:24px;margin-bottom:24px}' +
      '.console-head h1{font:500 clamp(28px,5vw,54px)/1 ' + serif + ';letter-spacing:-.035em;color:var(--a)}' +
      '.console-head p{font:11px ' + mono + ';color:var(--m);text-align:right;max-width:28ch}' +
      '.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}' +
      '.metric{background:' + dSurface + ';border:1px solid rgba(255,255,255,.1);border-radius:var(--radius);padding:20px;min-height:190px;display:flex;flex-direction:column}' +
      '.metric-kind{font:10px ' + mono + ';letter-spacing:.14em;text-transform:uppercase;color:var(--a);opacity:.8}' +
      '.metric strong{font:600 clamp(28px,4vw,48px)/1 ' + sans + ';letter-spacing:-.04em;margin-top:28px;color:#f1f5f9}' +
      '.metric h2{font:500 13px ' + sans + ';margin-top:8px;color:#cbd5e1}' +
      '.metric-foot{display:flex;align-items:end;justify-content:space-between;gap:8px;margin-top:auto;padding-top:22px;font:10px ' + mono + ';color:' + dMuted + '}' +
      '.metric svg{width:120px;height:28px;overflow:visible}.metric path{fill:none;stroke:' + dAccent + ';stroke-width:2;stroke-linecap:round;stroke-linejoin:round;opacity:.8}' +
      '.provenance{font:11px ' + mono + ';color:' + dMuted + ';margin-top:18px}' +
      '@media(max-width:820px){.metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:480px){.console-head{display:block}.console-head p{text-align:left;margin-top:12px}.metrics{grid-template-columns:1fr}}';
    var body = '<main class="console"><header class="console-head"><div><span class="metric-kind">' + esc(label) + '</span><h1>' + esc(content.title) + '</h1></div><p>Source-backed signals<br>no invented trends</p></header><section class="metrics" aria-label="Source metrics">' + cards + '</section><p class="provenance">Facts are quoted from the source; counts are derived from extracted structure.</p></main>';
    return pageWithPalette(content.title, css, body, dGround, dAccent, dMuted, dSurface, '#e6edf3');
  }

  function pageWithPalette(title, css, body, customGround, customAccent, customMuted, customSurface, customInk) {
    var saved = { ground: ground, accent: accent, muted: muted, surface: surface, ink: ink };
    ground = customGround; accent = customAccent; muted = customMuted; surface = customSurface; ink = customInk;
    var result = page(title, css, body);
    ground = saved.ground; accent = saved.accent; muted = saved.muted; surface = saved.surface; ink = saved.ink;
    return result;
  }

  function infographic() {
    var light = isLight(ground);
    var border = light ? 'rgba(15,18,24,.14)' : 'rgba(255,255,255,.14)';
    var rows = anchors.map(function(anchor, index) {
      var fact = facts[index];
      var width = fact ? factBarWidth(fact, facts) : 24 + ((anchor.length * 7) % 58);
      var value = fact && fact.value ? fact.value : 'anchor signal';
      return '<tr><th scope="row">' + esc(anchor) + '</th><td><span class="bar" style="width:' + width + '%"></span></td><td>' + esc(value) + '</td></tr>';
    }).join('');
    var factualRows = facts.filter(function(fact) { return fact.value; }).map(function(fact) {
      return '<tr><th scope="row">' + esc(fact.label) + '</th><td>' + esc(fact.value) + '</td><td>' + esc(fact.kind) + '</td></tr>';
    }).join('');
    var timeline = content.dates.length >= 2 ? '<section class="timeline"><span class="eyebrow">Sequence in source</span><div>' + content.dates.slice(0, 8).map(function(date, index) {
      return '<span><b>' + esc(date) + '</b><small>' + esc(anchors[index % anchors.length]) + '</small></span>';
    }).join('') + '</div></section>' : '';
    var numeric = firstNumericValue(content.numbers);
    var iso = numeric ? '<section class="isotype"><span class="eyebrow">One unit = one source count</span><div>' + repeat('<i aria-hidden="true"></i>', Math.min(Math.max(numeric, 1), 24)) + '</div></section>' : '';
    var css = 'body{font-family:' + sans + ';background:var(--g);color:var(--i)}' +
      '.poster{max-width:980px;margin:0 auto;padding:clamp(28px,6vw,76px) 28px 90px}' +
      '.poster-head{border-top:8px solid var(--a);padding-top:18px;max-width:760px}' +
      '.eyebrow{font:10px ' + mono + ';letter-spacing:.18em;text-transform:uppercase;color:var(--a)}' +
      'h1{font:400 clamp(42px,8vw,86px)/.9 ' + serif + ';letter-spacing:-.05em;margin-top:16px;max-width:10ch}' +
      '.deck{font:17px/1.65 ' + sans + ';max-width:58ch;opacity:.72;margin:22px 0 56px}' +
      '.chart{border-top:1px solid ' + border + ';border-bottom:1px solid ' + border + ';padding:18px 0 22px}.chart table,.data table{border-collapse:collapse;width:100%}' +
      '.chart th{font:500 14px ' + sans + ';text-align:left;width:30%;padding:11px 14px 11px 0}.chart td{padding:11px 0;vertical-align:middle}.chart td:nth-child(2){width:55%;padding-right:18px}.chart td:last-child{font:12px ' + mono + ';color:var(--m);text-align:right;white-space:nowrap}' +
      '.bar{display:block;height:18px;background:var(--a);border-radius:1px;transform-origin:left center;animation:grow .8s cubic-bezier(.2,.8,.2,1) both}.chart tr:nth-child(2) .bar{animation-delay:.08s}.chart tr:nth-child(3) .bar{animation-delay:.16s}@keyframes grow{from{transform:scaleX(0)}to{transform:scaleX(1)}}' +
      '.timeline{padding:48px 0;border-bottom:1px solid ' + border + '}.timeline>div{display:flex;gap:0;margin-top:20px;overflow-x:auto;padding-bottom:8px}.timeline span{min-width:120px;padding:12px 14px 0 0;border-top:2px solid var(--a);margin-right:14px}.timeline b{display:block;font:600 15px ' + mono + ';color:var(--a)}.timeline small{display:block;margin-top:6px;font-size:12px;opacity:.62}' +
      '.isotype{padding:48px 0;border-bottom:1px solid ' + border + '}.isotype>div{display:flex;gap:5px;flex-wrap:wrap;margin-top:18px}.isotype i{display:block;width:18px;height:28px;background:var(--m);border-radius:2px}' +
      '.data{padding-top:42px}.data table{font:12px ' + mono + '}.data th,.data td{text-align:left;padding:10px 12px 10px 0;border-bottom:1px solid ' + border + '}.data th{color:var(--m);font-weight:400}' +
      '.note{font:11px/1.6 ' + mono + ';color:var(--m);margin-top:18px}';
    var body = '<main class="poster"><header class="poster-head"><span class="eyebrow">' + esc(label) + '</span><h1>' + esc(content.title) + '</h1><p class="deck">' + esc(paragraphAt(0, anchors[0])) + '</p></header><section class="chart" aria-label="Content signals"><table><tbody>' + rows + '</tbody></table><p class="note">' + (facts.length ? 'Bars use only source facts; unnumbered anchors are labeled as signals.' : 'No numeric facts were found, so bars show relative anchor text length—not invented measurements.') + '</p></section>' + timeline + iso + (factualRows ? '<section class="data"><span class="eyebrow">Lossless source facts</span><table><thead><tr><th>Label</th><th>Value</th><th>Kind</th></tr></thead><tbody>' + factualRows + '</tbody></table></section>' : '') + '</main>';
    return page(content.title + ' — poster', css, body);
  }

  function artistic() {
    var words = content.title.split(/\s+/).filter(Boolean).map(function(word, index) {
      return '<span class="word word-' + (index % 4) + '">' + esc(word) + '</span>';
    }).join(' ');
    var filaments = anchors.map(function(anchor, index) {
      var hash = hashString(anchor + index);
      var y = 70 + (hash % 270);
      var bend = 80 + ((hash >>> 4) % 150);
      return '<path d="M0 ' + y + ' C160 ' + (y - bend) + ' 340 ' + (y + bend) + ' 760 ' + (y - 30 - index * 16) + '"/>';
    }).join('');
    var css = 'body{font-family:' + sans + ';background:var(--g);color:var(--i)}' +
      '.art{min-height:100vh;position:relative;display:grid;place-items:center;overflow:hidden;padding:64px 28px}' +
      '.field{position:absolute;inset:0;width:100%;height:100%;opacity:.42;mix-blend-mode:screen}.field path{fill:none;stroke:var(--m);stroke-width:1;stroke-dasharray:4 12;animation:drift 18s linear infinite}@keyframes drift{to{stroke-dashoffset:-160}}' +
      '.copy{position:relative;z-index:1;max-width:980px;width:100%;transform:translateX(var(--drift));}' +
      '.eyebrow{font:10px ' + mono + ';letter-spacing:.2em;text-transform:uppercase;color:var(--a)}' +
      '.title{font:400 clamp(56px,13vw,170px)/.78 ' + serif + ';letter-spacing:-.075em;margin-top:24px;max-width:9ch;color:var(--a);text-wrap:balance}.word{display:inline-block;margin-right:.12em}.word-1{font-style:italic;color:var(--m)}.word-2{transform:translateY(.12em)}.word-3{text-decoration:underline;text-decoration-thickness:2px;text-underline-offset:.1em}' +
      '.caption{max-width:42ch;margin:40px 0 0 12%;font-size:15px;line-height:1.75;opacity:.72}.anchors{margin:44px 0 0 12%;display:flex;flex-wrap:wrap;gap:8px}.anchors span{font:10px ' + mono + ';letter-spacing:.1em;text-transform:uppercase;border:1px solid var(--m);padding:7px 10px;border-radius:999px;color:var(--m)}' +
      '@media(max-width:620px){.copy{transform:none}.caption,.anchors{margin-left:0}.field{opacity:.25}}';
    var body = '<main class="art"><svg class="field" viewBox="0 0 760 420" preserveAspectRatio="none" aria-hidden="true">' + filaments + '</svg><div class="copy"><span class="eyebrow">' + esc(label) + '</span><h1 class="title">' + words + '</h1><p class="caption">' + esc(paragraphAt(0, anchors[0])) + '</p><div class="anchors" aria-label="Source anchors">' + anchors.map(function(anchor) { return '<span>' + esc(anchor) + '</span>'; }).join('') + '</div></div></main>';
    return page(content.title, css, body);
  }

  function cinematic() {
    var chapters = anchors.map(function(anchor, index) {
      return '<article class="chapter" id="chapter-' + index + '"><span class="chapter-no">' + String(index + 1).padStart(2, '0') + '</span><h2>' + esc(anchor) + '</h2><p>' + esc(paragraphAt(index, anchor)) + '</p></article>';
    }).join('');
    var css = 'body{font-family:' + sans + ';background:var(--g);color:var(--i)}' +
      '.scene{background:var(--g)}.opening{min-height:100svh;display:grid;place-items:center;position:relative;padding:48px 28px;text-align:center;isolation:isolate}.opening::before{content:"";position:absolute;inset:0;background:radial-gradient(ellipse 60% 55% at 50% 38%,var(--a),transparent 70%);opacity:.18;z-index:-1}.opening::after{content:"";position:absolute;width:1px;height:22vh;bottom:0;left:50%;background:linear-gradient(var(--a),transparent);opacity:.55}.opening-inner{max-width:900px}.eyebrow{font:10px ' + mono + ';letter-spacing:.2em;text-transform:uppercase;color:var(--a)}' +
      '.opening h1{font:400 clamp(54px,12vw,150px)/.84 ' + serif + ';letter-spacing:-.07em;color:var(--a);margin-top:24px;text-wrap:balance}.opening p{font-size:15px;line-height:1.6;opacity:.55;margin:26px auto 0;max-width:48ch}.continue{display:inline-block;margin-top:54px;font:10px ' + mono + ';letter-spacing:.16em;text-transform:uppercase;color:var(--m);text-decoration:none}.chapter{min-height:82svh;max-width:760px;margin:0 auto;display:grid;align-content:center;padding:100px 28px;position:relative;animation:rise both linear;animation-timeline:view();animation-range:entry 10% cover 38%}.chapter::before{content:"";position:absolute;left:28px;top:0;bottom:0;width:1px;background:var(--m);opacity:.25}.chapter-no{font:11px ' + mono + ';color:var(--a);margin-left:24px}.chapter h2{font:400 clamp(42px,8vw,92px)/.9 ' + serif + ';letter-spacing:-.055em;color:var(--a);max-width:8ch;margin:20px 0 24px 24px}.chapter p{font-size:18px;line-height:1.75;max-width:54ch;opacity:.7;margin-left:24px}@keyframes rise{from{opacity:0;transform:translateY(28px)}to{opacity:1;transform:none}}@supports not (animation-timeline:view()){.chapter{animation:none}}';
    var body = '<main class="scene"><section class="opening"><div class="opening-inner"><span class="eyebrow">' + esc(label) + '</span><h1>' + esc(content.title) + '</h1><p>' + esc(paragraphAt(0, anchors[0])) + '</p><a class="continue" href="#chapter-0">Enter the source ↓</a></div></section>' + chapters + '</main>';
    return page(content.title, css, body);
  }

  function photography() {
    var plates = anchors.map(function(anchor, index) {
      var wide = index % 3 === 0 ? 'wide' : '';
      return '<figure class="plate ' + wide + '">' + plateArt(anchor, index, accent, muted, ink) + '<figcaption><span>' + String(index + 1).padStart(2, '0') + '</span><strong>' + esc(anchor) + '</strong></figcaption></figure>';
    }).join('');
    var css = 'body{font-family:' + sans + ';background:var(--g);color:var(--i)}' +
      '.folio{max-width:1120px;margin:0 auto;padding:32px 28px 90px}.folio-head{display:flex;justify-content:space-between;align-items:baseline;gap:20px;border-bottom:1px solid rgba(255,255,255,.14);padding:18px 0 22px;margin-bottom:18px}.folio-head h1{font:400 clamp(34px,7vw,78px)/.9 ' + serif + ';letter-spacing:-.05em;max-width:9ch;color:var(--a)}.folio-head p{font:10px ' + mono + ';color:var(--m);text-transform:uppercase;letter-spacing:.15em}.gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.plate{position:relative;min-height:300px;overflow:hidden;border-radius:calc(var(--radius) / 2);background:var(--s)}.plate.wide{grid-column:span 2;min-height:420px}.plate svg{position:absolute;inset:0;width:100%;height:100%;transition:transform .35s ease}.plate:hover svg{transform:scale(1.04) rotate(var(--tilt))}.plate figcaption{position:absolute;left:0;right:0;bottom:0;display:flex;gap:12px;align-items:baseline;padding:24px 18px 16px;color:#fff;background:linear-gradient(transparent,rgba(0,0,0,.72))}.plate figcaption span{font:10px ' + mono + ';opacity:.62}.plate figcaption strong{font:400 22px ' + serif + '}.plate svg text{font-family:' + svgSans + ';font-size:13px;letter-spacing:.08em;text-transform:uppercase}.plate svg .orbit{transform-origin:50% 50%;animation:orbit 12s linear infinite}@keyframes orbit{to{transform:rotate(360deg)}}@media(max-width:760px){.gallery{grid-template-columns:repeat(2,1fr)}.plate.wide{grid-column:span 2}}@media(max-width:480px){.gallery{grid-template-columns:1fr}.plate,.plate.wide{grid-column:span 1;min-height:300px}}';
    var body = '<main class="folio"><header class="folio-head"><h1>' + esc(content.title) + '</h1><p>' + anchors.length + ' visual studies</p></header><section class="gallery" aria-label="Source anchor studies">' + plates + '</section></main>';
    return page(content.title + ' — folio', css, body);
  }

  function svg() {
    var cx = 210, cy = 210;
    var nodes = anchors.slice(0, 5).map(function(anchor, index) {
      var angle = -Math.PI / 2 + (index / Math.max(anchors.length, 1)) * Math.PI * 2;
      var x = cx + Math.cos(angle) * 128;
      var y = cy + Math.sin(angle) * 128;
      var labelX = 408;
      var labelY = 74 + index * 58;
      return '<path class="connector" d="M ' + x.toFixed(1) + ' ' + y.toFixed(1) + ' L ' + (labelX - 14) + ' ' + labelY + '"/><circle class="node node-' + index + '" cx="' + x.toFixed(1) + '" cy="' + y.toFixed(1) + '" r="5"/><text x="' + labelX + '" y="' + (labelY + 4) + '">' + esc(anchor) + '</text>';
    }).join('');
    var poly = [];
    for (var i = 0; i < 10; i++) {
      var angle = -Math.PI / 2 + i * Math.PI / 5;
      var radius = i % 2 ? 42 : 92;
      poly.push((cx + Math.cos(angle) * radius).toFixed(1) + ',' + (cy + Math.sin(angle) * radius).toFixed(1));
    }
    var css = 'body{font-family:' + sans + ';background:var(--g);color:var(--i);display:grid;place-items:center;min-height:100svh;padding:24px}.diagram{width:min(100%,860px)}.diagram h1{font:400 clamp(30px,6vw,64px)/.95 ' + serif + ';letter-spacing:-.04em;color:var(--a);margin-bottom:18px}.diagram .sub{font-size:14px;line-height:1.6;opacity:.62;max-width:52ch;margin-bottom:28px}.diagram svg{display:block;width:100%;height:auto;overflow:visible}.diagram .frame{fill:var(--s);stroke:var(--m);stroke-width:1;opacity:.72}.diagram .ring{fill:none;stroke:var(--m);stroke-width:1;stroke-dasharray:3 9;opacity:.7;animation:spin 22s linear infinite;transform-origin:' + cx + 'px ' + cy + 'px}.diagram .core{fill:var(--a);animation:breathe 3.6s ease-in-out infinite;transform-origin:' + cx + 'px ' + cy + 'px}.diagram .hole{fill:var(--g)}.diagram .connector{fill:none;stroke:var(--m);stroke-width:1;stroke-dasharray:2 5;opacity:.7}.diagram .node{fill:var(--a);stroke:var(--g);stroke-width:3}.diagram text{font-family:' + svgSans + ';font-size:13px;fill:var(--i)}@keyframes spin{to{transform:rotate(360deg)}}@keyframes breathe{50%{transform:scale(1.06)}}@media(max-width:600px){.diagram text{font-size:11px}}';
    var body = '<main class="diagram"><span class="eyebrow">' + esc(label) + '</span><h1>' + esc(content.title) + '</h1><p class="sub">A living map of the source anchors. Marks stay in the field; names stay in the gutter.</p><svg viewBox="0 0 620 440" role="img" aria-labelledby="svg-title svg-desc"><title id="svg-title">' + esc(content.title) + ' anchor diagram</title><desc id="svg-desc">A central content-derived mark connected to ' + esc(anchors.join(', ')) + '.</desc><rect class="frame" x="1" y="1" width="618" height="438" rx="4"/><circle class="ring" cx="' + cx + '" cy="' + cy + '" r="128"/><polygon class="core" points="' + poly.join(' ') + '"/><circle class="hole" cx="' + cx + '" cy="' + cy + '" r="8"/>' + nodes + '</svg></main>';
    return page(content.title + ' — SVG', css, body);
  }

  function threejs() {
    var faceColors = [accent, tint(accent, .2), muted, shade(accent, .16), tint(muted, .16), accent];
    var script = '(function(){' +
      'var c=document.getElementById("orbit-canvas"),ctx=c.getContext("2d"),view=document.getElementById("orbit-view"),status=document.getElementById("orbit-status");' +
      'var rx=.28,ry=' + (variation.tilt / 10).toFixed(2) + ',drag=false,lastX=0,lastY=0,reduced=window.matchMedia&&window.matchMedia("(prefers-reduced-motion: reduce)").matches;' +
      'function resize(){var d=Math.min(window.devicePixelRatio||1,2),w=c.clientWidth,h=c.clientHeight;c.width=w*d;c.height=h*d;ctx.setTransform(d,0,0,d,0,0);draw()}' +
      'function project(x,y,z){var cy=Math.cos(ry),sy=Math.sin(ry),cx=Math.cos(rx),sx=Math.sin(rx),x1=x*cy-z*sy,z1=x*sy+z*cy,y1=y*cx-z1*sx,z2=y*sx+z1*cx;return{x:x1,y:y1,d:z2}}' +
      'function draw(){var w=c.clientWidth,h=c.clientHeight;ctx.clearRect(0,0,w,h);var ox=w/2,oy=h/2,scale=Math.min(w,h)*.27;var faces=[[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1]],[[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]],[[-1,-1,-1],[-1,1,-1],[-1,1,1],[-1,-1,1]],[[1,-1,-1],[1,1,-1],[1,1,1],[1,-1,1]],[[-1,-1,-1],[1,-1,-1],[1,-1,1],[-1,-1,1]],[[-1,1,-1],[1,1,-1],[1,1,1],[-1,1,1]]];var projected=faces.map(function(face){return face.map(function(v){var q=project(v[0],v[1],v[2]);return{x:ox+q.x*scale,y:oy+q.y*scale,d:q.d}})});projected.sort(function(a,b){return a[0].d-b[0].d});projected.forEach(function(face,i){ctx.beginPath();face.forEach(function(q,j){j?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.closePath();ctx.fillStyle="' + faceColors[0] + '";var cols=[' + faceColors.map(function(c) { return '"' + c + '"'; }).join(',') + '];ctx.fillStyle=cols[i];ctx.globalAlpha=.86;ctx.fill();ctx.globalAlpha=1;ctx.strokeStyle="' + ground + '";ctx.lineWidth=1;ctx.stroke()});}' +
      'function orbit(e){if(!drag)return;ry+=(e.clientX-lastX)*.012;rx+=(e.clientY-lastY)*.012;lastX=e.clientX;lastY=e.clientY;status.textContent="Orbit adjusted";draw()}' +
      'c.addEventListener("pointerdown",function(e){drag=true;lastX=e.clientX;lastY=e.clientY;c.setPointerCapture(e.pointerId)});c.addEventListener("pointermove",orbit);c.addEventListener("pointerup",function(){drag=false});c.addEventListener("pointercancel",function(){drag=false});' +
      'c.addEventListener("keydown",function(e){if(e.key==="ArrowLeft"){ry-=.12}else if(e.key==="ArrowRight"){ry+=.12}else if(e.key==="ArrowUp"){rx-=.12}else if(e.key==="ArrowDown"){rx+=.12}else{return}e.preventDefault();status.textContent="Keyboard orbit adjusted";draw()});' +
      'function tick(){if(!reduced&&!drag){ry+=.0025;draw()}window.requestAnimationFrame(tick)}window.addEventListener("resize",resize);resize();tick()' +
      '})()';
    var css = 'body{font-family:' + sans + ';background:var(--g);color:var(--i);display:flex;flex-direction:column;min-height:100svh}#orbit-view{flex:1;min-height:260px;position:relative}canvas{display:block;width:100%;height:100%;min-height:260px;touch-action:none;cursor:grab}canvas:active{cursor:grabbing}.orbit-note{position:absolute;left:24px;top:22px;font:10px ' + mono + ';letter-spacing:.12em;text-transform:uppercase;color:var(--m);pointer-events:none}.orbit-bar{display:flex;justify-content:space-between;gap:18px;align-items:baseline;flex-wrap:wrap;padding:18px 24px;border-top:1px solid rgba(255,255,255,.14)}.orbit-bar h1{font:400 22px ' + serif + ';color:var(--a)}.orbit-bar p{font:11px ' + mono + ';color:var(--m)}.orbit-status{position:absolute;left:-9999px}.orbit-facts{display:flex;gap:8px;flex-wrap:wrap}.orbit-facts span{font:10px ' + mono + ';color:var(--m);border:1px solid var(--m);padding:5px 8px;border-radius:999px}@media(max-width:520px){.orbit-bar{display:block}.orbit-bar p{margin-top:8px}}';
    var body = '<main id="orbit-view"><canvas id="orbit-canvas" tabindex="0" role="img" aria-label="Interactive content-derived 3D view of ' + esc(content.title) + '"></canvas><span class="orbit-note">drag or use arrow keys</span><span id="orbit-status" class="orbit-status" aria-live="polite">Interactive view ready</span></main><footer class="orbit-bar"><div><h1>' + esc(content.title) + '</h1><div class="orbit-facts">' + anchors.slice(0, 4).map(function(anchor) { return '<span>' + esc(anchor) + '</span>'; }).join('') + '</div></div><p>offline canvas · no external assets</p></footer>';
    return page(content.title + ' — 3D', css, body, script);
  }

  function simulation() {
    var dated = content.dates.length > 0;
    var eventValues = dated ? content.dates.slice(0, 8) : anchors.slice(0, 8).map(function(_, index) { return 'step ' + (index + 1); });
    var events = eventValues.map(function(value, index) {
      return { value: value, label: anchors[index % Math.max(anchors.length, 1)] || 'Source', index: index };
    });
    var eventButtons = events.map(function(event) {
      return '<button type="button" class="event" data-index="' + event.index + '"><span>' + esc(event.value) + '</span><strong>' + esc(event.label) + '</strong></button>';
    }).join('');
    var max = Math.max(events.length - 1, 0);
    var css = 'body{font-family:' + sans + ';background:var(--g);color:var(--i);padding:clamp(24px,6vw,70px) 28px}.clock{max-width:1040px;margin:0 auto}.eyebrow{font:10px ' + mono + ';letter-spacing:.18em;text-transform:uppercase;color:var(--a)}.clock h1{font:400 clamp(40px,8vw,90px)/.9 ' + serif + ';letter-spacing:-.055em;color:var(--a);max-width:10ch;margin-top:18px}.clock .intro{font-size:16px;line-height:1.7;opacity:.68;max-width:52ch;margin-top:22px}.rail{position:relative;margin:78px 0 36px;padding:0 8px}.rail::before{content:"";position:absolute;left:8px;right:8px;top:50%;height:2px;background:var(--m);opacity:.4}.events{position:relative;display:flex;justify-content:space-between;gap:8px}.event{position:relative;z-index:1;display:flex;flex-direction:column;align-items:center;gap:8px;min-width:0;background:transparent;color:var(--i);border:0;cursor:pointer;text-align:center}.event::before{content:"";width:14px;height:14px;border:3px solid var(--g);border-radius:50%;background:var(--m);box-shadow:0 0 0 1px var(--m);transition:transform .18s ease}.event:hover::before,.event.active::before{background:var(--a);transform:scale(1.25)}.event span{font:12px ' + mono + ';color:var(--a);white-space:nowrap}.event strong{font:400 12px ' + serif + ';max-width:120px;white-space:normal}.controls{display:flex;align-items:center;gap:14px;flex-wrap:wrap}.control{border:0;border-radius:999px;padding:12px 18px;background:var(--a);color:var(--g);font-weight:700;cursor:pointer}.control.secondary{background:transparent;color:var(--i);box-shadow:inset 0 0 0 1px var(--m)}.readout{font:12px ' + mono + ';color:var(--m)}input[type=range]{width:100%;accent-color:var(--a);margin-top:26px}.note{font:11px/1.6 ' + mono + ';color:var(--m);margin-top:24px}@media(max-width:620px){.rail{overflow-x:auto;padding-bottom:16px}.events{min-width:680px}.event strong{max-width:90px}}';
    var script = '(function(){var slider=document.getElementById("timeline-slider"),play=document.getElementById("timeline-play"),speed=document.getElementById("timeline-speed"),readout=document.getElementById("timeline-readout"),buttons=[].slice.call(document.querySelectorAll(".event")),playing=false,rate=1,timer=null;function set(index){index=Math.max(0,Math.min(' + max + ',Number(index)||0));slider.value=index;buttons.forEach(function(button){button.classList.toggle("active",Number(button.dataset.index)===index)});readout.textContent="' + (dated ? 'Date' : 'Step') + ': "+buttons[index].textContent.replace(/\\s+/g," ").trim()}function stop(){playing=false;play.textContent="▶ Play";if(timer)window.clearInterval(timer);timer=null}function start(){if(playing)return;playing=true;play.textContent="⏸ Pause";timer=window.setInterval(function(){var next=Number(slider.value)+1;if(next>' + max + '){stop();return}set(next)},Math.max(180,900/rate))}slider.addEventListener("input",function(){stop();set(this.value)});buttons.forEach(function(button){button.addEventListener("click",function(){stop();set(button.dataset.index)})});play.addEventListener("click",function(){playing?stop():start()});speed.addEventListener("click",function(){rate=rate===1?2:rate===2?4:1;speed.textContent=rate+"× speed";if(playing){stop();start()}});set(0)})()';
    var body = '<main class="clock"><span class="eyebrow">' + esc(label) + '</span><h1>' + esc(content.title) + '</h1><p class="intro">' + esc(paragraphAt(0, anchors[0])) + '</p><section class="rail" aria-label="Source ' + (dated ? 'dates' : 'sequence') + '"><div class="events">' + eventButtons + '</div></section><input id="timeline-slider" type="range" min="0" max="' + max + '" value="0" step="1" aria-label="Move through source ' + (dated ? 'dates' : 'sequence') + '"><div class="controls"><button type="button" class="control" id="timeline-play">▶ Play</button><button type="button" class="control secondary" id="timeline-speed">1× speed</button><output class="readout" id="timeline-readout" aria-live="polite"></output></div><p class="note">The clock follows ' + (dated ? 'dates found in the source.' : 'the order of source anchors because no dates were found.') + '</p></main>';
    return page(content.title + ' — timeline', css, body, script);
  }
}

function factsFor(content) {
  var facts = [];
  content.numbers.forEach(function(value, index) {
    facts.push({ value: value, label: content.anchors[index % Math.max(content.anchors.length, 1)] || 'Source measure', kind: 'number' });
  });
  content.dates.forEach(function(value, index) {
    facts.push({ value: value, label: content.anchors[index % Math.max(content.anchors.length, 1)] || 'Source date', kind: 'date' });
  });
  return facts.slice(0, 10);
}

function metricCards(facts, anchors) {
  var metrics = facts.slice(0, 4).map(function(fact) {
    return { value: fact.value, label: fact.label, kind: 'source ' + fact.kind, detail: 'quoted from source' };
  });
  var counts = [
    { value: anchors.length, label: 'content anchors' },
  ];
  while (metrics.length < 4 && counts.length) {
    var count = counts.shift();
    metrics.push({ value: String(count.value), label: count.label, kind: 'derived count', detail: 'counted in source' });
  }
  return metrics.slice(0, 4);
}

function firstNumericValue(values) {
  for (var i = 0; i < values.length; i++) {
    var match = String(values[i]).replace(/,/g, '').match(/\d+(?:\.\d+)?/);
    if (match) return Math.floor(Number(match[0]));
  }
  return 0;
}

function factBarWidth(fact, facts) {
  var value = firstNumericValue([fact.value]);
  var max = facts.reduce(function(high, item) { return Math.max(high, firstNumericValue([item.value])); }, 0);
  return value && max ? Math.max(12, Math.round(value / max * 100)) : 24;
}

function sparkPath(label, index) {
  var hash = hashString(label + index);
  var path = '';
  for (var i = 0; i < 12; i++) {
    var x = i * 10.5;
    var y = 5 + ((hash >>> (i % 16)) % 18);
    path += (i ? 'L' : 'M') + x.toFixed(1) + ' ' + y.toFixed(1) + ' ';
  }
  return path;
}

function plateArt(anchor, index, accent, muted, ink) {
  var hash = hashString(anchor + ':' + index);
  var hue = hash % 360;
  var x = 110 + (hash % 220);
  var y = 110 + ((hash >>> 5) % 120);
  var r = 40 + ((hash >>> 9) % 90);
  var path = 'M0 300 C' + (100 + (hash % 160)) + ' ' + (80 + (hash % 100)) + ' ' + (300 + (hash % 190)) + ' ' + (280 - (hash % 120)) + ' S520 ' + (150 + (hash % 120)) + ' 600 ' + (80 + (hash % 170));
  return '<svg viewBox="0 0 600 400" role="img" aria-label="Abstract visual study for ' + esc(anchor) + '"><defs><linearGradient id="g' + index + '" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="' + tint(accent, .12) + '"/><stop offset="1" stop-color="' + shade(muted, .2) + '"/></linearGradient></defs><rect width="600" height="400" fill="url(#g' + index + ')"/><circle class="orbit" cx="' + x + '" cy="' + y + '" r="' + r + '" fill="none" stroke="' + accent + '" stroke-width="2" opacity=".7"/><circle cx="' + (x + r / 2).toFixed(0) + '" cy="' + (y - r / 2).toFixed(0) + '" r="8" fill="' + accent + '"/><path d="' + path + '" fill="none" stroke="' + ink + '" stroke-width="1.5" opacity=".5"/><text x="28" y="48" fill="' + ink + '" opacity=".72">' + esc(anchor) + '</text><text x="570" y="370" text-anchor="end" fill="' + accent + '" opacity=".78">0' + (index + 1) + '</text></svg>';
}

function repeat(value, count) {
  var result = '';
  for (var i = 0; i < count; i++) result += value;
  return result;
}

function profileLabel(name) {
  var labels = {
    saas: 'Signal / systems', tech: 'Logic / tools', essay: 'Personal / reflective',
    literary: 'Literary / considered', restaurant: 'Table / atmosphere', food: 'Kitchen / craft',
    nature: 'Field / living', outdoor: 'Field / expedition', ocean: 'Tide / depth',
    night: 'Night / luminous', editorial: 'Press / considered', minimal: 'Quiet / essential',
    default: 'Content / considered',
  };
  return labels[name] || labels.default;
}

function hashString(value) {
  var hash = 2166136261;
  String(value).split('').forEach(function(char) {
    hash ^= char.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  });
  return hash >>> 0;
}

function esc(value) {
  if (!value) return '';
  return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

function makeRNG(seed) {
  var state = seed | 0;
  return function() {
    state = state + 0x6D2B79F5 | 0;
    var t = Math.imul(state ^ state >>> 15, 1 | state);
    t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  };
}

function shuffle(values, rng) {
  var result = values.slice();
  for (var i = result.length - 1; i > 0; i--) {
    var j = Math.floor(rng() * (i + 1));
    var temp = result[i]; result[i] = result[j]; result[j] = temp;
  }
  return result;
}

var generateApi = { generate: generate, TOKENS: TOKENS, TOKEN_DESCRIPTIONS: TOKEN_DESCRIPTIONS };
if (typeof module !== 'undefined' && module.exports) module.exports = generateApi;
if (typeof window !== 'undefined') window.ReimagineGenerate = generateApi;

/* src/auto.js */
/**
 * Design Auto — an inspectable, model-agnostic autopilot for reimagine-it.
 *
 * Auto chooses a coherent token from extracted evidence, creates candidates,
 * evaluates generated artifacts, and returns the strongest result. It never
 * edits the source and never calls a model by itself; a host harness can use
 * the structured plan as context for a richer model-led pass.
 */

var generateApi = typeof module !== 'undefined' && module.exports
  ? require('./generate')
  : (typeof window !== 'undefined' ? window.ReimagineGenerate : {});

var DEFAULT_CANDIDATES = ['webpage', 'landing', 'dashboard', 'infographic', 'cinematic', 'artistic', 'photography', 'svg', '3js', 'simulation'];

function normaliseCount(value) {
  value = Number(value);
  return Number.isFinite(value) ? Math.max(1, Math.min(3, Math.floor(value))) : 1;
}

function scoreToken(token, content) {
  var score = 0;
  var text = [content.title].concat(content.headings || [], content.paragraphs || [], content.anchors || []).join(' ').toLowerCase();
  var facts = (content.numbers || []).length + (content.dates || []).length;
  var links = (content.links || []).length;
  var items = (content.items || []).length;
  if (token === 'dashboard') score += facts * 5 + (/metric|status|uptime|latency|observability|operations|analytics|performance/.test(text) ? 18 : 0);
  if (token === 'infographic') score += facts * 3 + items * 2 + (/compare|timeline|history|statistics|data|report|survey/.test(text) ? 14 : 0);
  if (token === 'webpage') score += (content.paragraphs || []).length + (content.headings || []).length;
  if (token === 'simulation') score += (content.dates || []).length * 6 + (/process|sequence|steps?|timeline|round|version|flow/.test(text) ? 16 : 0);
  if (token === 'simulation' && (content.dates || []).length < 2) score -= 12;
  if (token === '3js') score += (/space|orbit|planet|map|landscape|architecture|room|journey|explore/.test(text) ? 13 : 0) + (content.anchors || []).length;
  if (token === 'svg') score += (/diagram|system|network|map|relationship|brand|identity|signal/.test(text) ? 13 : 0) + links;
  if (token === 'landing') score += links * 3 + (/product|service|startup|contact|signup|pricing|launch/.test(text) ? 15 : 0);
  if (token === 'photography') score += items * 2 + (/portfolio|gallery|studio|collection|visual|photo|image/.test(text) ? 13 : 0);
  if (token === 'cinematic') score += (/story|journey|chapter|film|cinema|night|dream|light/.test(text) ? 15 : 0) + (content.paragraphs || []).length;
  if (token === 'artistic') score += (/poem|poetry|essay|memory|color|art|creative|voice|emotion/.test(text) ? 13 : 0) + Math.max(0, 8 - facts);
  if (token === 'webpage') score += 5 + (content.paragraphs || []).length * 2 + (content.headings || []).length;
  return score;
}

function chooseTokens(content, count) {
  count = normaliseCount(count || 3);
  return DEFAULT_CANDIDATES.map(function(token) {
    return { token: token, score: scoreToken(token, content) };
  }).sort(function(a, b) {
    return b.score - a.score || DEFAULT_CANDIDATES.indexOf(a.token) - DEFAULT_CANDIDATES.indexOf(b.token);
  }).slice(0, count);
}

function buildPlan(content, options) {
  options = options || {};
  var candidates = chooseTokens(content, options.candidates || 3);
  var selected = candidates[0];
  return {
    mode: 'auto',
    title: content.title,
    profile: content.profile,
    density: content.density,
    recommendation: selected.token,
    candidates: candidates,
    anchors: (content.anchors || []).slice(0, 5),
    facts: { headings: (content.headings || []).length, paragraphs: (content.paragraphs || []).length, items: (content.items || []).length, dates: (content.dates || []).length, numbers: (content.numbers || []).length, links: (content.links || []).length },
    rationale: rationale(selected.token, content),
    next: 'Generate the recommended token, audit it, then show it to the client before applying any source edit.',
    safety: ['source is read-only', 'facts remain source-backed', 'output is standalone HTML', 'candidate must pass audit before selection'],
  };
}

function rationale(token, content) {
  var facts = (content.numbers || []).length + (content.dates || []).length;
  var anchors = (content.anchors || []).length;
  var reasons = {
    webpage: 'The source benefits from a measured reading hierarchy.',
    landing: 'The source has an outward-facing action or product-like structure.',
    dashboard: 'The source contains enough measurable signals for an operational view.',
    infographic: 'The source contains facts or lists that benefit from a shared visual scale.',
    cinematic: 'The source has narrative language that benefits from paced chapters.',
    artistic: 'The source is sparse or expressive enough for a poster-like composition.',
    photography: 'The source has a collection of items that can become visual studies.',
    svg: 'The source names enough anchors to map into a compact living diagram.',
    '3js': 'The source has spatial or exploratory language suited to an orbitable field.',
    simulation: 'The source has a sequence or dated progression that can be scrubbed.',
  };
  return reasons[token] + ' Evidence: ' + anchors + ' anchors, ' + facts + ' measurable facts.';
}

function escapeHtml(value) {
  return String(value || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

function qualityScore(output, content) {
  var sourceTitle = escapeHtml(content.title);
  var anchors = (content.anchors || []).slice(0, 5);
  var score = 0;
  var checks = [];
  function check(name, passed, points) {
    checks.push({ name: name, passed: passed });
    if (passed) score += points;
  }
  check('standalone HTML', /^<!doctype html>/i.test(output), 18);
  check('title preserved', !sourceTitle || output.indexOf(sourceTitle) >= 0, 18);
  check('source anchors retained', !anchors.length || anchors.some(function(anchor) { return output.indexOf(escapeHtml(anchor)) >= 0; }), 16);
  check('focus-visible', output.indexOf('focus-visible') >= 0, 10);
  check('reduced motion', output.indexOf('prefers-reduced-motion') >= 0, 10);
  check('selection styling', output.indexOf('::selection') >= 0, 8);
  check('no placeholder copy', !/(?:lorem ipsum|placeholder|title goes here|sample text|\bTBD\b)/i.test(output), 10);
  check('no external asset fetch', !/(?:src|href)=["']https?:\/\/[^"']+\.(?:js|css|woff2?|png|jpe?g|gif|svg|webp)(?:["'\s])/i.test(output), 10);
  return { score: score, checks: checks };
}

function randomSeed() {
  return Math.floor(Math.random() * 0x7fffffff);
}

function autoGenerate(content, options) {
  options = options || {};
  var plan = buildPlan(content, { candidates: options.candidates || 3 });
  var baseSeed = options.seed === undefined ? randomSeed() : Number(options.seed);
  if (!Number.isSafeInteger(baseSeed)) baseSeed = randomSeed();
  var evaluated = plan.candidates.map(function(candidate, index) {
    var seed = (baseSeed + hashString(candidate.token) + (index + 1) * 7919) | 0;
    var output = generateApi.generate({ content: content, token: candidate.token, seed: seed, brief: options.brief });
    var quality = qualityScore(output, content);
    var passed = quality.checks.every(function(check) { return check.passed; });
    return { token: candidate.token, seed: seed, fit: candidate.score, quality: quality.score, total: candidate.score * 2 + quality.score, checks: quality.checks, output: output, passed: passed };
  });
  if (!evaluated.some(function(candidate) { return candidate.passed; })) {
    throw new Error('no Design Auto candidate passed the craft checks');
  }
  evaluated = evaluated.filter(function(candidate) { return candidate.passed; }).sort(function(a, b) {
    return b.total - a.total || b.quality - a.quality || a.token.localeCompare(b.token);
  }).slice(0, plan.candidates.length);
  var selected = evaluated[0];
  return {
    mode: 'auto', token: selected.token, seed: selected.seed, output: selected.output,
    score: selected.total, rationale: plan.rationale,
    candidates: evaluated.map(function(candidate) {
      return { token: candidate.token, seed: candidate.seed, fit: candidate.fit, quality: candidate.quality, total: candidate.total, checks: candidate.checks };
    }), plan: plan,
  };
}

function hashString(value) {
  var hash = 2166136261;
  String(value || '').split('').forEach(function(char) {
    hash ^= char.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  });
  return hash >>> 0;
}

var autoApi = { DEFAULT_CANDIDATES: DEFAULT_CANDIDATES, scoreToken: scoreToken, chooseTokens: chooseTokens, buildPlan: buildPlan, qualityScore: qualityScore, autoGenerate: autoGenerate };
if (typeof module !== 'undefined' && module.exports) module.exports = autoApi;
if (typeof window !== 'undefined') window.ReimagineAuto = autoApi;
